convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_002-a.pdf ../figures/PhotonGood0_pt.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_002-b.pdf ../figures/mT.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_002-c.pdf ../figures/m3.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_002-d.pdf ../figures/mLtight0Gamma.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_002-e.pdf ../figures/ltight0GammadR.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_002-f.pdf ../figures/photonJetdR.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_003-a.pdf ../figures/WJets_mT_e.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_003-b.pdf ../figures/WJets_mT_mu.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_004-a.pdf ../figures/mLtight0Gamma_e.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_004-b.pdf ../figures/mLtight0Gamma_mu.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_006.pdf ../figures/regions_VG3e_VG3mu_VG4pe_VG4pmu_misDY3_misDY4p.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_007.pdf ../figures/regions_SR3eM3_SR3muM3_SR4peM3_SR4pmuM3.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_008.pdf ../figures/summaryResult.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_009-a.pdf ../figures/unfolded_spectrum_fromSyst_ptg_log.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_009-b.pdf ../figures/unfolded_spectrum_fromSyst_absEta.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_009-c.pdf ../figures/unfolded_spectrum_fromSyst_dRlg.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_010-a.pdf ../figures/corrMatrix_ptg.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_010-b.pdf ../figures/corrMatrix_eta.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_010-c.pdf ../figures/corrMatrix_dR.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_011-a.pdf ../figures/eft_ptg_3e.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_011-b.pdf ../figures/eft_ptg_3mu.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_011-c.pdf ../figures/eft_ptg_4pe.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_011-d.pdf ../figures/eft_ptg_4pmu.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_012-a.pdf ../figures/ctZ_wExp_wBkg_profiled.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_012-b.pdf ../figures/ctZI_wExp_wBkg_profiled.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_012-c.pdf ../figures/ctZ_wExp_wBkg.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_012-d.pdf ../figures/ctZI_wExp_wBkg.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/allgemein/documentation/TOP-18-010/Figure_013.pdf ../figures/ctZ_ctZI_wBkg.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/thesis/addMat/Figures/corrMatrix_stat_dRlg.pdf ../figures/corrMatrix_stat_dR.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/thesis/addMat/Figures/corrMatrix_stat_eta.pdf ../figures/corrMatrix_stat_eta.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/thesis/addMat/Figures/corrMatrix_stat_ptg.pdf ../figures/corrMatrix_stat_ptg.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/thesis/addMat/Figures/covMatrix_stat_dRlg.pdf ../figures/covMatrix_stat_dR.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/thesis/addMat/Figures/covMatrix_stat_eta.pdf ../figures/covMatrix_stat_eta.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/thesis/addMat/Figures/covMatrix_stat_ptg.pdf ../figures/covMatrix_stat_ptg.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/thesis/addMat/Figures/covMatrix_syst_dRlg.pdf ../figures/covMatrix_syst_dR.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/thesis/addMat/Figures/covMatrix_syst_eta.pdf ../figures/covMatrix_syst_eta.png
convert -flatten -density 300 -fuzz 1% -trim +repage ~/Documents/Dokumente/PhD/thesis/addMat/Figures/covMatrix_syst_ptg.pdf ../figures/covMatrix_syst_ptg.png
