python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix nominal
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix ISRUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix FSRUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix ISRDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix FSRDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix ScaleUpUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix ScaleNomUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix ScaleUpNom
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix ScaleDownDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix ScaleNomDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix ScaleDownNom
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix reweightTopPt
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix erdOn
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix GluonMove
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix QCDbased
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix photonSFUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix photonSFDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix photonElectronVetoSFUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix photonElectronVetoSFDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix eResUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix eResDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix eScaleUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix eScaleDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jerUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jerDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix TuneUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix TuneDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix TriggerUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix TriggerDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix BTag_SF_b_Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix BTag_SF_b_Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix BTag_SF_l_Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix BTag_SF_l_Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix LeptonTrackingTightSFUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix LeptonTrackingTightSFDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix LeptonTightSFUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix LeptonTightSFDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix LeptonTightSFStatUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix LeptonTightSFStatDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix LeptonTightSFSystUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix LeptonTightSFSystDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix L1PrefireUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix L1PrefireDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix PUUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix PUDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesFlavorQCDUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesFlavorQCDDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesRelativeBalUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesRelativeBalDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesHFUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesHFDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesBBEC1Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesBBEC1Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesEC2Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesEC2Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesAbsoluteUp
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesAbsoluteDown
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesAbsolute_2016Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesAbsolute_2016Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesHF_2016Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesHF_2016Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesEC2_2016Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesEC2_2016Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesRelativeSample_2016Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesRelativeSample_2016Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesBBEC1_2016Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesBBEC1_2016Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesAbsolute_2017Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesAbsolute_2017Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesHF_2017Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesHF_2017Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesEC2_2017Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesEC2_2017Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesRelativeSample_2017Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesRelativeSample_2017Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesBBEC1_2017Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesBBEC1_2017Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesAbsolute_2018Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesAbsolute_2018Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesHF_2018Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesHF_2018Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesEC2_2018Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesEC2_2018Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesRelativeSample_2018Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesRelativeSample_2018Down
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesBBEC1_2018Up
python unfolding_uncertainty.py --settings observed_ptG_RunII --useMatrix jesBBEC1_2018Down
