#python systematicVariation.py --postfit --photonCat --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection misDY2 --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection misDY2 --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection misDY2 --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection misDY2 --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection misDY3 --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection misDY3 --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection misDY3 --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection misDY3 --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection misDY4p --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection misDY4p --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection misDY4p --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection misDY4p --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection misDY3p --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection misDY3p --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection misDY3p --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection misDY3p --binning 20 20 120 --variable PhotonGood0_pt --mode e
#python systematicVariation.py --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection DY3 --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection DY4p --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection DY3 --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection DY4p --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection DY3 --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection DY4p --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection DY3 --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection DY4p --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection DY3 --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection DY4p --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection DY3 --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection DY4p --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection DY3 --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection DY4p --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection DY3 --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection DY4p --binning 15 81.1 101.1 --variable mlltight --mode SFtight
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets2 --binning 20 30 230 --variable LeptonTight0_pt --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets2 --binning 20 30 230 --variable LeptonTight0_pt --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3 --binning 20 30 230 --variable LeptonTight0_pt --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3 --binning 20 30 230 --variable LeptonTight0_pt --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets4p --binning 20 30 230 --variable LeptonTight0_pt --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets4p --binning 20 30 230 --variable LeptonTight0_pt --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT2 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT2 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT2 --binning 20 30 230 --variable LeptonTight0_pt --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT2 --binning 20 30 230 --variable LeptonTight0_pt --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3 --binning 20 30 230 --variable LeptonTight0_pt --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3 --binning 20 30 230 --variable LeptonTight0_pt --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT4p --binning 20 30 230 --variable LeptonTight0_pt --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT4p --binning 20 30 230 --variable LeptonTight0_pt --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3p --binning 20 -2.4 2.4 --variable JetGood0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3p --binning 20 -2.4 2.4 --variable JetGood0_eta --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3p --binning 20 30 230 --variable JetGood0_pt --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3p --binning 20 30 230 --variable JetGood0_pt --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3p --binning 20 0 200 --variable MET_pt --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3p --binning 20 0 200 --variable MET_pt --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3p --binning 22 60 500 --variable m3 --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3p --binning 22 60 500 --variable m3 --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3p --binning 20 0 600 --variable ht --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3p --binning 20 0 600 --variable ht --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3p --binning 20 0 200 --variable mT --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3p --binning 20 0 200 --variable mT --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3p --binning 20 -2.4 2.4 --variable JetGood0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3p --binning 20 -2.4 2.4 --variable JetGood0_eta --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3p --binning 20 30 230 --variable JetGood0_pt --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3p --binning 20 30 230 --variable JetGood0_pt --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3p --binning 20 0 200 --variable MET_pt --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3p --binning 20 0 200 --variable MET_pt --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3p --binning 22 60 500 --variable m3 --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3p --binning 22 60 500 --variable m3 --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3p --binning 20 0 600 --variable ht --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3p --binning 20 0 600 --variable ht --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3p --binning 20 0 200 --variable mT --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3p --binning 20 0 200 --variable mT --mode e
#python systematicVariation.py --inclQCDTF --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection WJets2 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode mu
#python systematicVariation.py --inclQCDTF --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection WJets2 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets2 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets2 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode e
#python systematicVariation.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1a --selection VGmis3p --binning 19 23 175 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1a --selection VGmis3p --binning 19 23 175 --variable mLtight0Gamma --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1a --selection VGmis3p --binning 19 23 175 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --postfit --photonCat --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1a --selection VGmis3p --binning 19 23 175 --variable mLtight0Gamma --mode e
#python systematicVariation.py --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --postfit --photonCat --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --postfit --photonCat --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --postfit --photonCat --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --postfit --photonCat --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --postfit --photonCat --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --photonCat --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --photonCat --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --photonCat --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --photonCat --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --photonCat --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --photonCat --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
#python systematicVariation.py --photonCat --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode mu
#python systematicVariation.py --photonCat --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection VGmis3p --binning 12 0 240 --variable mLtight0Gamma --mode e
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT3 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT4p --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection TT4p --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode e
#python systematicVariation.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection WJets3 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection WJets3 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode e
#python systematicVariation.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection WJets3 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection WJets3 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode e
#python systematicVariation.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection WJets3 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection WJets3 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets3 --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode e
#python systematicVariation.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection WJets4p --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection WJets4p --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode e
#python systematicVariation.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection WJets4p --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection WJets4p --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode e
#python systematicVariation.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection WJets4p --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection WJets4p --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode e
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets4p --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode mu
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection WJets4p --binning 20 -2.4 2.4 --variable LeptonTight0_eta --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake3 --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu#
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection fake4p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
#python systematicVariation.py --postfit --photonCat --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection misTT2 --binning 2 0 2 --variable nElectronTight --mode all
#python systematicVariation.py --postfit --photonCat --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection misTT2 --binning 2 0 2 --variable nElectronTight --mode all
#python systematicVariation.py --postfit --photonCat --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection misTT2 --binning 2 0 2 --variable nElectronTight --mode all
#python systematicVariation.py --postfit --photonCat --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection misTT2 --binning 2 0 2 --variable nElectronTight --mode all
#python systematicVariation.py --photonCat --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection misTT2 --binning 2 0 2 --variable nElectronTight --mode all
#python systematicVariation.py --photonCat --variation central --year 2017 --plot_directory 102X_TTG_ppv49_v1 --selection misTT2 --binning 2 0 2 --variable nElectronTight --mode all
#python systematicVariation.py --photonCat --variation central --year 2018 --plot_directory 102X_TTG_ppv49_v1 --selection misTT2 --binning 2 0 2 --variable nElectronTight --mode all
#python systematicVariation.py --photonCat --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection misTT2 --binning 2 0 2 --variable nElectronTight --mode all
#python systematicVariation.py --postfit --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection SR3p --binning 20 20 120 --variable PhotonGood0_pt --mode all
#python systematicVariation.py --postfit --photonCat --variation central --year 2016 --plot_directory 102X_TTG_ppv49_v1 --selection SR3p --binning 20 20 120 --variable PhotonGood0_pt --mode all
#python systematicVariation.py --postfit --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection SR3p --binning 20 20 120 --variable PhotonGood0_pt --mode all
#python systematicVariation.py --postfit --photonCat --variation central --year RunII --plot_directory 102X_TTG_ppv49_v1 --selection SR3p --binning 20 20 120 --variable PhotonGood0_pt --mode all
