python systematicVariationFakes.py --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --year 2016 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --year 2017 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --year 2018 --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --photonCat --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode mu
python systematicVariationFakes.py --photonCat --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highSieieNoChgIso --binning 20 0 22.82 --variable "PhotonNoChgIsoNoSieie0_pfRelIso03_chg*PhotonNoChgIsoNoSieie0_pt" --mode e
python systematicVariationFakes.py --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut lowChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
python systematicVariationFakes.py --photonCat --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode e
python systematicVariationFakes.py --photonCat --postfit --year RunII --plot_directory 102X_TTG_ppv45_v1 --selection fake3p --addCut highChgIsoNoSieie --binning 40 0.005 0.025 --variable PhotonNoChgIsoNoSieie0_sieie --mode mu
