python ../regions/fitResults.py --year 2016 --substituteCard SR3Unfold    --carddir /mnt/hephy/cms/lukas.lechner/TTGammaEFT/cache/analysis/2016/limits/cardFiles/defaultSetup/observed/ --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_misTT2_incl --postFit --cores 1 --cacheHistogram --bkgSubstracted --plotRegionPlot
python ../regions/fitResults.py --year 2016 --substituteCard SR3Unfold_e  --carddir /mnt/hephy/cms/lukas.lechner/TTGammaEFT/cache/analysis/2016/limits/cardFiles/defaultSetup/observed/ --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_misTT2_incl --postFit --cores 1 --cacheHistogram --bkgSubstracted --plotRegionPlot
python ../regions/fitResults.py --year 2016 --substituteCard SR3Unfold_mu --carddir /mnt/hephy/cms/lukas.lechner/TTGammaEFT/cache/analysis/2016/limits/cardFiles/defaultSetup/observed/ --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_misTT2_incl --postFit --cores 1 --cacheHistogram --bkgSubstracted --plotRegionPlot

python ../regions/fitResults.py --year 2016 --substituteCard SR4pUnfold    --carddir /mnt/hephy/cms/lukas.lechner/TTGammaEFT/cache/analysis/2016/limits/cardFiles/defaultSetup/observed/ --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_misTT2_incl --postFit --cores 1 --cacheHistogram --bkgSubstracted --plotRegionPlot
python ../regions/fitResults.py --year 2016 --substituteCard SR4pUnfold_e  --carddir /mnt/hephy/cms/lukas.lechner/TTGammaEFT/cache/analysis/2016/limits/cardFiles/defaultSetup/observed/ --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_misTT2_incl --postFit --cores 1 --cacheHistogram --bkgSubstracted --plotRegionPlot
python ../regions/fitResults.py --year 2016 --substituteCard SR4pUnfold_mu --carddir /mnt/hephy/cms/lukas.lechner/TTGammaEFT/cache/analysis/2016/limits/cardFiles/defaultSetup/observed/ --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_misTT2_incl --postFit --cores 1 --cacheHistogram --bkgSubstracted --plotRegionPlot


python ../regions/fitResults.py --year 2016 --substituteCard SR3EtaUnfold    --carddir /mnt/hephy/cms/lukas.lechner/TTGammaEFT/cache/analysis/2016/limits/cardFiles/defaultSetup/observed/ --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_misTT2_incl --postFit --cores 1 --cacheHistogram --bkgSubstracted --plotRegionPlot
python ../regions/fitResults.py --year 2016 --substituteCard SR3EtaUnfold_e  --carddir /mnt/hephy/cms/lukas.lechner/TTGammaEFT/cache/analysis/2016/limits/cardFiles/defaultSetup/observed/ --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_misTT2_incl --postFit --cores 1 --cacheHistogram --bkgSubstracted --plotRegionPlot
python ../regions/fitResults.py --year 2016 --substituteCard SR3EtaUnfold_mu --carddir /mnt/hephy/cms/lukas.lechner/TTGammaEFT/cache/analysis/2016/limits/cardFiles/defaultSetup/observed/ --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_misTT2_incl --postFit --cores 1 --cacheHistogram --bkgSubstracted --plotRegionPlot

python ../regions/fitResults.py --year 2016 --substituteCard SR4pEtaUnfold    --carddir /mnt/hephy/cms/lukas.lechner/TTGammaEFT/cache/analysis/2016/limits/cardFiles/defaultSetup/observed/ --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_misTT2_incl --postFit --cores 1 --cacheHistogram --bkgSubstracted --plotRegionPlot
python ../regions/fitResults.py --year 2016 --substituteCard SR4pEtaUnfold_e  --carddir /mnt/hephy/cms/lukas.lechner/TTGammaEFT/cache/analysis/2016/limits/cardFiles/defaultSetup/observed/ --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_misTT2_incl --postFit --cores 1 --cacheHistogram --bkgSubstracted --plotRegionPlot
python ../regions/fitResults.py --year 2016 --substituteCard SR4pEtaUnfold_mu --carddir /mnt/hephy/cms/lukas.lechner/TTGammaEFT/cache/analysis/2016/limits/cardFiles/defaultSetup/observed/ --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_misTT2_incl --postFit --cores 1 --cacheHistogram --bkgSubstracted --plotRegionPlot

