python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet1-nNoChgIsoNoSieieBTag0   --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet1                         --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet1p                        --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet2-nNoChgIsoNoSieieBTag0   --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet2                         --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet3-nNoChgIsoNoSieieBTag1p  --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet4p-nNoChgIsoNoSieieBTag1p --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3

python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet1-mll40                                --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet1-nNoChgIsoNoSieieBTag0-offZSFll-mll40 --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet1p-mll40                               --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet2-mll40                                --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet2-nNoChgIsoNoSieieBTag0-offZSFll-mll40 --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet3-mll40                                --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5


python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet1-nNoChgIsoNoSieieBTag0   --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet1                         --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet1p                        --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet2-nNoChgIsoNoSieieBTag0   --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet2                         --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet3-nNoChgIsoNoSieieBTag1p  --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet4p-nNoChgIsoNoSieieBTag1p --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3

python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet1-mll40                                --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet1-nNoChgIsoNoSieieBTag0-offZSFll-mll40 --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet1p-mll40                               --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet2-mll40                                --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet2-nNoChgIsoNoSieieBTag0-offZSFll-mll40 --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet3-mll40                                --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5




python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet1-nBTag0   --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet1                         --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet1p                        --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet2-nBTag0   --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet2                         --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet3-nBTag1p  --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3

python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet1-mll40                                --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet1-nBTag0-offZSFll-mll40 --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet1p-mll40                               --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet2-mll40                                --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet2-nBTag0-offZSFll-mll40 --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet3-mll40                                --plot_directory 102X_TTG_ppv25_v1Classic --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5


python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet1-nBTag0   --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet1                         --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet1p                        --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet2-nBTag0   --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet2                         --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet3-nBTag1p  --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nJet4p-nBTag1p --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3

python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet1-mll40                                --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet1-nBTag0-offZSFll-mll40 --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet1p-mll40                               --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet2-mll40                                --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet2-nBTag0-offZSFll-mll40 --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso_classic.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nJet3-mll40                                --plot_directory 102X_TTG_ppv25_v1Classic --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
