python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet4p-nNoChgIsoNoSieieBTag1p                       --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet2p-nNoChgIsoNoSieieBTag1p-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5

python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet1-nNoChgIsoNoSieieBTag0-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet1-nNoChgIsoNoSieieBTag1p-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet2-nNoChgIsoNoSieieBTag0-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet2-nNoChgIsoNoSieieBTag1p-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet3p-nNoChgIsoNoSieieBTag0-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet3p-nNoChgIsoNoSieieBTag1p-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5

python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet1-nNoChgIsoNoSieieBTag0                       --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet2-nNoChgIsoNoSieieBTag0                       --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet2-nNoChgIsoNoSieieBTag1p                       --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet3-nNoChgIsoNoSieieBTag0                       --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet3-nNoChgIsoNoSieieBTag1p                       --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet4p-nNoChgIsoNoSieieBTag0                      --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet4p-nNoChgIsoNoSieieBTag1p                      --plot_directory 102X_TTG_ppv25_v1 --sideband chgIso --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3

python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet4p-nNoChgIsoNoSieieBTag1p                       --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet2p-nNoChgIsoNoSieieBTag1p-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5

python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet1-nNoChgIsoNoSieieBTag0-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet1-nNoChgIsoNoSieieBTag1p-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet2-nNoChgIsoNoSieieBTag0-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet2-nNoChgIsoNoSieieBTag1p-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet3p-nNoChgIsoNoSieieBTag0-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight2-nLepVeto2-nNoChgIsoNoSieieJet3p-nNoChgIsoNoSieieBTag1p-offZSFll-mll40        --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT5

python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet1-nNoChgIsoNoSieieBTag0                       --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet2-nNoChgIsoNoSieieBTag0                       --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet2-nNoChgIsoNoSieieBTag1p                       --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet3-nNoChgIsoNoSieieBTag0                       --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet3-nNoChgIsoNoSieieBTag1p                       --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet4p-nNoChgIsoNoSieieBTag0                      --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3
python ratioPlots_chgIso.py --normalize --noData --onlyTT --year 2016 --selection nLepTight1-nLepVeto1-nNoChgIsoNoSieieJet4p-nNoChgIsoNoSieieBTag1p                      --plot_directory 102X_TTG_ppv25_v1 --sideband sieie --categoryPhoton PhotonNoChgIsoNoSieie0 #SPLIT3

