
#python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR4pPtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR4pPtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2017 --substituteCard SR4pPtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2018 --substituteCard SR4pPtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR4pPtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2016
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR4pPtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2017
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR4pPtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2018

#python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR3PtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR3PtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2017 --substituteCard SR3PtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2018 --substituteCard SR3PtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR3PtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2016
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR3PtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2017
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR3PtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2018

#python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR4pdRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR4pdRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2017 --substituteCard SR4pdRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2018 --substituteCard SR4pdRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR4pdRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2016
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR4pdRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2017
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR4pdRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2018

#python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR3dRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR3dRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2017 --substituteCard SR3dRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2018 --substituteCard SR3dRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR3dRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2016
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR3dRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2017
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR3dRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2018

#python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR4pAbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR4pAbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2017 --substituteCard SR4pAbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2018 --substituteCard SR4pAbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR4pAbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2016
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR4pAbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2017
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR4pAbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2018

#python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR3AbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR3AbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2017 --substituteCard SR3AbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
#python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2018 --substituteCard SR3AbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR3AbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2016
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR3AbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2017
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3M3_SR4pM3_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --substituteCard SR3AbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2018
