python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR3pPtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2017 --substituteCard SR3pPtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2018 --substituteCard SR3pPtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --plotYear 2016 --substituteCard SR3pPtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --plotYear 2017 --substituteCard SR3pPtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --plotYear 2018 --substituteCard SR3pPtUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF --year combined --substituteCard SR3pPtUnfold_addDYSF_addMisIDSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2016
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF --year combined --substituteCard SR3pPtUnfold_addDYSF_addMisIDSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2017
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF --year combined --substituteCard SR3pPtUnfold_addDYSF_addMisIDSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2018

python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR3pdRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2017 --substituteCard SR3pdRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2018 --substituteCard SR3pdRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --plotYear 2016 --substituteCard SR3pdRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --plotYear 2017 --substituteCard SR3pdRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --plotYear 2018 --substituteCard SR3pdRUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF --year combined --substituteCard SR3pdRUnfold_addDYSF_addMisIDSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2016
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF --year combined --substituteCard SR3pdRUnfold_addDYSF_addMisIDSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2017
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF --year combined --substituteCard SR3pdRUnfold_addDYSF_addMisIDSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2018

python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2016 --substituteCard SR3pAbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2017 --substituteCard SR3pAbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year 2018 --substituteCard SR3pAbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --plotYear 2016 --substituteCard SR3pAbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --plotYear 2017 --substituteCard SR3pAbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF --year combined --plotYear 2018 --substituteCard SR3pAbsEtaUnfold_addDYSF --bkgSubstracted --plotRegionPlot --postFit
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF --year combined --substituteCard SR3pAbsEtaUnfold_addDYSF_addMisIDSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2016
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF --year combined --substituteCard SR3pAbsEtaUnfold_addDYSF_addMisIDSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2017
python fitResults.py --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF --year combined --substituteCard SR3pAbsEtaUnfold_addDYSF_addMisIDSF --bkgSubstracted --plotRegionPlot --postFit --expected --plotYear 2018
