python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2016 --substituteCard SR3pPtUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat --noFreeze
python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2016 --substituteCard SR3pdRUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat --noFreeze
python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2016 --substituteCard SR3pAbsEtaUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat --noFreeze

python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2017 --substituteCard SR3pPtUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat --noFreeze 
python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2017 --substituteCard SR3pdRUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat --noFreeze
python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2017 --substituteCard SR3pAbsEtaUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat --noFreeze

python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2018 --substituteCard SR3pPtUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat --noFreeze
python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2018 --substituteCard SR3pdRUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat --noFreeze
python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2018 --substituteCard SR3pAbsEtaUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat --noFreeze
#
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2016 --substituteCard SR3pPtUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat --noFreeze
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2016 --substituteCard SR3pdRUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat --noFreeze
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2016 --substituteCard SR3pAbsEtaUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat --noFreeze

#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2017 --substituteCard SR3pPtUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat --noFreeze 
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2017 --substituteCard SR3pdRUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat --noFreeze
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2017 --substituteCard SR3pAbsEtaUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat --noFreeze

#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2018 --substituteCard SR3pPtUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat --noFreeze
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2018 --substituteCard SR3pdRUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat --noFreeze
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2018 --substituteCard SR3pAbsEtaUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat --noFreeze


#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2016 --substituteCard SR3pPtUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2016 --substituteCard SR3pdRUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2016 --substituteCard SR3pAbsEtaUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat

#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2017 --substituteCard SR3pPtUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat 
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2017 --substituteCard SR3pdRUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2017 --substituteCard SR3pAbsEtaUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat

#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2018 --substituteCard SR3pPtUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2018 --substituteCard SR3pdRUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/observed --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addPtBinnedUnc --cacheHistogram --year 2018 --substituteCard SR3pAbsEtaUnfold_addDYSF_addPtBinnedUnc --plotRegionPlot --postFit --plotNuisances all total MCStat

#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2016 --substituteCard SR3pPtUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2016 --substituteCard SR3pdRUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2016 --substituteCard SR3pAbsEtaUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat

#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2017 --substituteCard SR3pPtUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat 
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2017 --substituteCard SR3pdRUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2017 --substituteCard SR3pAbsEtaUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat

#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3PtUnfold_SR4pPtUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2018 --substituteCard SR3pPtUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3dRUnfold_SR4pdRUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2018 --substituteCard SR3pdRUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat
#python fitResultsNew.py --bkgSubstracted --carddir limits/cardFiles/defaultSetup/expected --cardfile SR3AbsEtaUnfold_SR4pAbsEtaUnfold_VG3_VG4p_misDY3_misDY4p_addDYSF_addMisIDSF_addPtBinnedUnc --cacheHistogram --year 2018 --substituteCard SR3pAbsEtaUnfold_addDYSF_addMisIDSF_addPtBinnedUnc --plotRegionPlot --expected --postFit --plotNuisances all total MCStat

